### ISSUE TITLE
不太具体

### ISSUE THREAD

**Issue by jaredwangcode** [songxd/AndroidMultiChannelBuildTool-Java#1]
运行尝试打包以后各种错误,不知道是不是我的方式不对?能否详细点,谢谢!

**Comment by songxd** [comment]
本段代码原理只是在apk文件中写入一个一空文件，通过读取空文件的名称来获取渠道名称，具体分析可看*_https://github.com/GavinCT/AndroidMultiChannelBuildTool *_ 本代码是java版本 原文用python

**Comment by jaredwangcode** [comment]
之前在您的基础上进行了一些修改,现已没问题投入使用了.非常感谢您!
